name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs: 
  build-linux-gcc:
    runs-on: ubuntu-22.04
    steps:
      - name: test & build astrogator
        run: |
          make run_tests
          make clean
          make build
        env:
          CC: gcc
