name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs: 
  build-linux-gcc:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@main

      - name: Test
        run: make run_tests
        env:
          CC: gcc

      - name: Clean
        run: make clean
        env:
          CC: gcc

      - name: Build
        run: make build
        env:
          CC: gcc
